drop table tblproperty_details;
CREATE TABLE `tblproperty_details` (
  `PID` int(11) NOT NULL,
  `WardNo` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `OldAssessmentNo` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `NewAssessmentNo` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `PropertyNo` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `BlockName` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `StreetName` varchar(345)  CHARACTER SET utf8 DEFAULT NULL,
  `PinCode` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `Latitude` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `Longitude` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `PropertyUsage` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `physical_property` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `property_type` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `property_class` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `Dimenstion` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `Length` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `Breadth` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `TotalArea` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `BuiltUpAreaLength` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `BuiltUpAreaBreadth` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `TotalBuiltUpArea` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `NoOfFloors` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `ResidenceType` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `TradeLicenceNo` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `WaterSeqNo` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `tblproperty_detailscol` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `NumberOfTaps` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `UGDSeqNo` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `PropertyAddress` varchar(445)  CHARACTER SET utf8 DEFAULT NULL,
  `OwnerAddress` varchar(345)  CHARACTER SET utf8 DEFAULT NULL,
  `OccupierName` varchar(345)  CHARACTER SET utf8 DEFAULT NULL,
  `OwnerFirstName` varchar(345)  CHARACTER SET utf8 DEFAULT NULL,
  `OwnerMiddleName` varchar(345)  CHARACTER SET utf8 DEFAULT NULL,
  `OwnerLastName` varchar(345)  CHARACTER SET utf8 DEFAULT NULL,
  `OwnerFirstNameEng` varchar(345)  CHARACTER SET utf8 DEFAULT NULL,
  `OwnerMiddleNameEng` varchar(345)  CHARACTER SET utf8 DEFAULT NULL,
  `OwnerLastNameEng` varchar(345)  CHARACTER SET utf8 DEFAULT NULL,
  `PhoneNo` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `MobileNo` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `Email` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `AdharNo` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `PageNo` varchar(345)  CHARACTER SET utf8 DEFAULT NULL,
  `RRNo` varchar(345)  CHARACTER SET utf8 DEFAULT NULL,
  `PropertyStatus` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  `AssessmentInitiatedYear` varchar(345) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`PID`)
);